### ISSUE TITLE
Start using sortinghat on existing indexes

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/sortinghat#112]
Hi,

I am ready to setup sortinghat, but wanted to verify e.g. double check on something. My dashboard has been running for over a year now. Based on primarily Grimoire-Elk and vanilla Elasticsearch and Kibana (5.4.x).

Can I install sortinghat and start using it, also on my existing indexes? 

I use p2o to import my data, I know I will have to add some parameters so that p2o will also start using sortinghat. I do not need to create new indexes? Sortinghat will just extend them further?

Thanks.

**Comment by jgbarah** [comment]
In short, you will need to re-enrich the data. That is, you can use either p2o or Mordred to re-enrich the data, telling it (I mean, telling p2o or Mordred) that you want to use SortingHat. That will inject all identities in the raw indexes in Sorting Hat, and produce new enriched indexes with identities.

Then, it is a matter of improving SortingHat data (by eg merging identities that you know are the same), and re-enrich the enriched indexes with the new SortingHat ids.

If you want, I can try to drive you through the process (I was about to write about that for the GrimoireLab tutorial). You can be my guinea pig for a while ;-)

**Comment by robinmuilwijk** [comment]
Hello Jesus,

I would love to get your help on this, it sounds a bit more complex than I had anticipated. Especially creating new enriched indexes. As I have created my own dashboards.

I am waiting for IT to give me some good dates to install sortinghat. I will do this myself, but I want to make sure they are available if my dashboard breaks, so they can put back a snapshot (hard lesson learned already).

Should I follow up with you through e-mail?

**Comment by jgbarah** [comment]
Great!

We can follow up in a ticket, if you don't mind this discussion being public: that way it could help some others. But if you prefer to go private, let's use email.

In case you prefer to go public, I suggest we open a ticket in chaoss/grimoirelab (formerly grimoirelab/grimoirelab), where we're discussing general stuff related to GrimoireLab, since more modules are going to be involved, in addition to Sorting Hat. We can later close this ticket mentioning that one.

Meanwhile, let me mention that now installation of Sorting Hat and all other components should be much easier. If you want, you can use pre-installed docker containers, have a look at https://grimoirelab.gitbooks.io/tutorial/mordred/mordred-in-a-container.html If you want, maybe I could help you, or your IT people, to move to that kind of deployment. Otherwise, installation via pip should be much more reliable now, too.

**Comment by robinmuilwijk** [comment]
I will open up a ticket on chaos/grimoirelab as soon as poissible. I will follow the pip install for sortinghat, as all the other modules and its installation is based on this method.

**Comment by robinmuilwijk** [comment]
I opened up https://github.com/chaoss/grimoirelab/issues/53 to continue this issue.
